version: '3'

networks:
  web:
    external: true

services:
  application:
    image: composer:2
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - web
    environment:
      TYPO3_CONTEXT: Development/InternalDns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testing.rule=Host(`testing.localhost`)"
      - "traefik.http.routers.testing.entrypoints=web"
      - "traefik.http.services.testing.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    restart: always
    command: php -S 0.0.0.0:80 -t public/
